#SPRING:
#  PROFILES: DEFAULT
#
#DATASOURCE:
#  MAP:
#      INITIALIZE: TRUE
#      DRIVER-CLASS-NAME: "COM.MYSQL.JDBC.DRIVER"
#      URL: "JDBC:MYSQL://LOCALHOST/WORLD?VERIFYSERVERCERTIFICATE?=FALSE&USESSL=FALSE"
#      USER-NAME: "ROOT"
#      PASSWORD: "ROOT"
#      INITIAL-SIZE: 10
#      MAX-ACTIVE: 10
#      MAX-IDLE: 10
#      MIN-IDLE: 10
#      MAX-WAIT: 3000
#  ADMIN:
#      INITIALIZE: TRUE
#      DRIVER-CLASS-NAME: "COM.MYSQL.JDBC.DRIVER"
#      URL: "JDBC:MYSQL://LOCALHOST/WORLD?VERIFYSERVERCERTIFICATE?=FALSE&USESSL=FALSE"
#      USER-NAME: "ROOT"
#      PASSWORD: "ROOT"
#      INITIAL-SIZE: 10
#      MAX-ACTIVE: 10
#      MAX-IDLE: 10
#      MIN-IDLE: 10
#      MAX-WAIT: 3000
